"""Sphinx configuration for the pdft documentation site."""

from __future__ import annotations

import os

# Keep doc builds from writing into the user's JAX compile cache.
os.environ.setdefault("PDFT_DISABLE_COMPILE_CACHE", "1")

import pdft

project = "pdft"
author = "zazabap"
copyright = "2026, zazabap"
release = pdft.__version__
version = ".".join(release.split(".")[:2])

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_gallery.gen_gallery",
]

source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
# CLAUDE.md points design specs at docs/superpowers/; the directory is not
# committed today, and this keeps it out of the site if it ever is.
exclude_patterns = ["_build", "superpowers", "Thumbs.db", ".DS_Store"]

# The docstrings use single backticks for code and object names; render them
# as code (linked when the name resolves) rather than as <cite> italics.
default_role = "py:obj"

# -- API reference -----------------------------------------------------------
autosummary_generate = True
# undoc-members: dataclass fields carry no docstrings, but their names and
# types are the useful part of e.g. RiemannianGD and TrainingResult.
autodoc_default_options = {"members": True, "undoc-members": True, "show-inheritance": True}
autodoc_member_order = "bysource"
autodoc_typehints = "description"
napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_use_rtype = False

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "jax": ("https://docs.jax.dev/en/latest", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
}
# Inventories are fetched over the network under -W; bound a hang, and if a
# host is down the fix is to re-run the build.
intersphinx_timeout = 30

myst_enable_extensions = ["colon_fence", "dollarmath", "substitution"]

# The upstream pin is read from the package so the docs cannot drift from it.
_upstream_repo, _upstream_sha = pdft.__upstream_ref__.split("@")
myst_substitutions = {
    "upstream_commit_link": (
        f"[`{_upstream_sha[:7]}`](https://github.com/{_upstream_repo}/tree/{_upstream_sha})"
    ),
    # Upstream notes, at the pinned commit rather than main so they match.
    "upstream_note_stepbystep": (
        f"[Step-by-step derivation](https://github.com/{_upstream_repo}/blob/{_upstream_sha}/note/stepbystep.pdf)"
    ),
    "upstream_note_main": (
        f"[Main notes](https://github.com/{_upstream_repo}/blob/{_upstream_sha}/note/main.pdf)"
    ),
}

# -- Example gallery ---------------------------------------------------------
# Each example runs at build time (a few seconds apiece) so the rendered
# pages carry real loss curves. The scripts write their PNGs to examples/out/,
# which is gitignored.
sphinx_gallery_conf = {
    "examples_dirs": "../examples",
    "gallery_dirs": "auto_examples",
    "filename_pattern": r".*\.py$",
    "download_all_examples": False,
    "remove_config_comments": True,
    "reference_url": {"pdft": None},
}

# -- HTML --------------------------------------------------------------------
# sphinx-book-theme, the theme JAX's documentation uses.
html_theme = "sphinx_book_theme"
html_title = f"pdft {release}"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
# Logo assets are generated by docs/logo/build_logo.py; edit that, not the SVGs.
html_favicon = "_static/favicon.png"
# The theme's default sidebar opens with a "Search / Ctrl+K" field; JAX's site
# does not show it, and the magnifier button in the article header remains.
html_sidebars = {"**": ["navbar-logo.html", "icon-links.html", "sbt-sidebar-nav.html"]}
html_theme_options = {
    "logo": {
        "image_light": "_static/logo-light.svg",
        "image_dark": "_static/logo-dark.svg",
        "alt_text": "pdft",
    },
    "repository_url": "https://github.com/zazabap/pdft",
    "use_repository_button": True,
    "use_issues_button": True,
    # Off: autosummary stubs and gallery pages are generated, so their
    # "edit this page" targets would 404.
    "use_edit_page_button": False,
    "use_download_button": False,
    "show_toc_level": 2,
    "home_page_in_toc": True,
    "navigation_with_keys": False,
    # No search field in the (hidden) top navbar either; the header icon remains.
    "navbar_persistent": [],
}
