"""Circuit machinery shared by every basis: gates, programs and the applier.

A family emits a Yao-style gate list; `compile_program` turns it into a
`Program` and the tensors in stored order (Hadamard-first, Yao little-endian
qubits); `CircuitCode` applies the program one gate at a time.
"""

from .builder import (
    GATE_KINDS,
    HADAMARD,
    REGISTERS,
    CircuitCode,
    Gate,
    Program,
    apply_circuit,
    apply_program,
    bit_reverse,
    check_qubits,
    compile_circuit,
    compile_program,
    controlled,
    controlled_phase_diag,
    cp_gate,
    extract_phase_from_cp,
    extract_phases,
    hadamard_gate,
    hadamards_then_layers,
    identity_tensor,
    is_compact_cp,
    phase_gate,
    register_width,
    select_last_n_cp_indices,
    two_registers,
    u4_from_phase,
    u4_gate,
)

__all__ = [
    "GATE_KINDS",
    "HADAMARD",
    "REGISTERS",
    "CircuitCode",
    "Gate",
    "Program",
    "apply_circuit",
    "apply_program",
    "bit_reverse",
    "check_qubits",
    "compile_circuit",
    "compile_program",
    "controlled",
    "controlled_phase_diag",
    "cp_gate",
    "extract_phase_from_cp",
    "extract_phases",
    "hadamard_gate",
    "hadamards_then_layers",
    "identity_tensor",
    "is_compact_cp",
    "phase_gate",
    "register_width",
    "select_last_n_cp_indices",
    "two_registers",
    "u4_from_phase",
    "u4_gate",
]
